// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIP4ofPLfn8au53fLznsVSpV9pHm0-NN8',
    appId: '1:890573643466:android:a2af43e5be30fb2cdc1e33',
    messagingSenderId: '890573643466',
    projectId: 'rc-apps-digital',
    storageBucket: 'rc-apps-digital.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9e06PKrjUXV9JGwQJwgoAK3MO5RWJ5HU',
    appId: '1:890573643466:ios:f06c9d6be594dec4dc1e33',
    messagingSenderId: '890573643466',
    projectId: 'rc-apps-digital',
    storageBucket: 'rc-apps-digital.firebasestorage.app',
    iosBundleId: 'com.example.agendaNails',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0p4JzDYLX_qKPFa7dIdPJymoddIHTNPU',
    appId: '1:890573643466:web:288ae4ebb8f6a684dc1e33',
    messagingSenderId: '890573643466',
    projectId: 'rc-apps-digital',
    authDomain: 'rc-apps-digital.firebaseapp.com',
    storageBucket: 'rc-apps-digital.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9e06PKrjUXV9JGwQJwgoAK3MO5RWJ5HU',
    appId: '1:890573643466:ios:f06c9d6be594dec4dc1e33',
    messagingSenderId: '890573643466',
    projectId: 'rc-apps-digital',
    storageBucket: 'rc-apps-digital.firebasestorage.app',
    iosBundleId: 'com.example.agendaNails',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0p4JzDYLX_qKPFa7dIdPJymoddIHTNPU',
    appId: '1:890573643466:web:5b80894e6e0a215fdc1e33',
    messagingSenderId: '890573643466',
    projectId: 'rc-apps-digital',
    authDomain: 'rc-apps-digital.firebaseapp.com',
    storageBucket: 'rc-apps-digital.firebasestorage.app',
  );
}
